version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - /app/node_modules  # 重要: コンテナの node_modules を上書きしない
    environment:
      - NODE_ENV=development
