version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules  
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0